# Generated by Django 4.2.3 on 2023-07-13 12:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('announcements', '0002_response'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Announcement',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='post',
            new_name='announcement',
        ),
    ]
