# Generated by Django 4.2.3 on 2023-07-14 10:37

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('announcements', '0003_rename_post_announcement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='text',
            field=ckeditor.fields.RichTextField(blank='True', null='True', verbose_name='Текст'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
