# Generated by Django 4.2.3 on 2023-07-14 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_announcement_text_alter_announcement_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterModelOptions(
            name='response',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
