# Generated by Django 4.2.3 on 2023-07-17 12:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0005_alter_announcement_options_alter_response_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='text',
            field=models.CharField(max_length=64, null=True, verbose_name='Текст комментария'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='dateCreation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='response',
            name='dateCreation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
