# Generated by Django 4.2.3 on 2023-07-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0008_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='text',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Текст комментария'),
        ),
    ]
