# Generated by Django 4.2.3 on 2023-07-22 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0012_alter_response_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Видео'),
        ),
    ]
